rdkcentral/meta-vendor-raspberrypi-dev

- conf/include/rdke-vendor-bbmask.inc
Reason for change: libwayland-egl libraries are packaged under wayland-default-egl
Test Procedure: Build and verify
Risks: Low
Priority: P1
> RDK-49475: Remove BBMASK for wayland bbappend

- recipes-core/packagegroups/packagegroup-vendor-layer.bb
require OSS vesion 3.0.3.
This is a temporary change until OSS fixes the wayland recipe.
> Add wayland-default-egl to packagegroup-vendor-layer

- recipes-core/packagegroups/packagegroup-vendor-layer.bb
Reason for change: Added the runtime dependency package group.
Test Procedure: build and verify.
Risks: low.
Signed-off-by: Dinesh_kumar2@comcast.com.
> RDKE-125 Integrate bluez5, bluetooth-mgr and bluetooth-core

- conf/include/vendor_pkg_versions.inc
- recipes-core/packagegroups/packagegroup-vendor-layer.bb
gstreamer1.0-rtsp-server is from OSS and is required for resolving the RDEPENDS error while building upper layers.
> RDKE-151: Add gstreamer1.0-rtsp-server in pkggrp

- conf/include/vendor_pkg_versions.inc
- recipes-graphics/userland/userland_git.bbappend
- recipes-kernel/android/android-raspberrypi.inc
Reason for change: Fix all floating tag/branch to a fixed SRCREV
Test Procedure: Build and Verify
Risks: Low
> RDKVREFPLT-3124: Recipe uses a floating tag/branch without a fixed SRCREV

- conf/template/local.conf.sample
Reason for change: To fix Exception: NotImplementedError in local.conf
> RDKVREFPLT-3133: Fix parse error in local.conf

- recipes-kernel/android/android-raspberrypi.inc
Reason for change: Fix build error get_cc_option: not found
> RDKVREFPLT-3127: android-raspberrypi 5.10 kernel build compile error

- recipes-bsp/bootfiles/rpi-cmdline.bbappend
- recipes-kernel/android/android-raspberrypi.inc
- recipes-kernel/android/android-raspberrypi_%.bbappend
Reason for change: kirkstone meta-raspberrypi upstream provides new bb (reciped-bsb/bootfiles/rpi-cmdline.bb) file for cmdline operation
> RDKVREFPLT-3127: Resolving build errors - android-raspberrypi do_deply

- conf/include/vendor_pkg_versions.inc
Update wayland-default-egl recipe to kirkstone version of wayland recipe(1.20.0)
> RDKVREFPLT-3153: Use kirkstone version of wayland-default-egl recipe

- recipes-halif/iarmmgrs/iarmmgrs-hal-raspberrypi4.bb
Latest MW requires PWRMGR and DEEPSLEEP HALSs as virtual.
> RDKVREFPLT-3162: MW HAL refactoring requirement

- conf/include/vendor_pkg_versions.inc
This includes the following:
- Stub implementation for dsHdmiIn.h
- Bugfix of REFPLTV-2489
> RDKVREFPLT-3687: use the latest DSHAL v1.0.4

- recipes-halif/mfrlibs/mfrlibs-hal-raspberrypi4.bb
Default change is point to a wrong one
```
root@raspberrypi4-64-rdke:~# ls -aslh /usr/bin/ | grep Flash
4 lrwxrwxrwx    1 root     root         202 Mar  9  2018 FlashApp -> /mnt/jenkins/workspace/RASPBERRYPI-VENDOR-Build/build-raspberrypi4-64-rdke/tmp/work/raspberrypi4-64-rdke-vendor-rdkmllib32-linux-gnueabi/lib32-mfrlibs-hal-raspberrypi4/1.0.3-r0/image/usr/bin/FlashApp.sh
12 -rwxr-xr-x    1 root     root       10.7K Mar  9  2018 FlashApp.sh
root@raspberrypi4-64-rdke:~#
```
With this change; it shall point to correct file in rootfs.
> RDKVREFPLT-3151: fix the symlink issue

- recipes-core/packagegroups/packagegroup-vendor-layer.bb
Update and align the vendor package version to v4.0.1 conveying Kirkstone support.
> RDKVREFPLTV-4051: rename pkggrp version to v4.0.1

- recipes-core/packagegroups/packagegroup-vendor-layer.bb
To convey kirkstone alignment and vedor releases; renamed vendor pkg version to 4.0.1
> Change vendor pkggrp version - PV to 4.0.1

- conf/include/vendor_pkg_versions.inc
Reason for Change: with v1.1.1 MW image reboots continuously. Revert to known good version.
> Revert PWRMGRHAL to v1.1.0

- conf/include/vendor_pkg_versions.inc
Reason for change: Cold launch of Xumo takes morethan 10 seconds. Set wayland compositor type as surface in wpeframework drop-in conf
> RDKVREFPLT-4254: sysint-soc repo release 1.1.0

- conf/include/vendor_pkg_versions.inc
- recipes-core/packagegroups/packagegroup-vendor-layer.bb
Reason for change: Enabling ac3 decoders in ffmpeg Test Procedure: Play ac3 streams using gst launch
Risks:High
Priority: P1
> REFPLTV-2609: Audio not heard for AC3 and EAC3 streams

- conf/include/vendor_pkg_versions.inc
- recipes-core/packagegroups/packagegroup-vendor-layer.bb
- [REFPLTV-2609: Audio not heard for AC3 and EAC3 streams](https://github.com/rdkcentral/meta-vendor-raspberrypi-dev/commit/5c7e9621b88e3b871bcdf30a4d5a547952dafa1e). ffmpeg added as VENDOR_LAYER_EXTENSION
- [REFPLTV-2594: sysint-soc update to v1.1.3](https://github.com/rdkcentral/meta-vendor-raspberrypi-dev/commit/241b0c328e53884e72a5ef97d561078398b999e4)
> REFPLTV-2609, REFPLTV-2594: update ffmpeg and sysint-soc to latest in main

- conf/include/vendor_pkg_versions.inc
- recipes-core/packagegroups/packagegroup-vendor-layer.bb
REFPLTV-2927: Vendor release 4.4.6
Fixes 
1] Toggling of cec control causes wpeframework crash
2] oem-first-boot.service not completing activation until internet is available.
3] Correct rdk-gstreamer-utils release tag to match with halif-headers
> REFPLTV-2927: Vendor release 4.4.6

- conf/include/vendor_pkg_versions.inc
**Reason for change:** Update the rdk-gstreamer-utils-platform and devicesettings-hal-raspberrypi4 recipe SRC_REV version.
**Risks:** High.
**Signed-off-by:** sundaramuneeswaran_muthuraj@comcast.com
> RDKEVL-4433: [RPI]Update the rdk-gstreamer-utils-platform and devicesettings-hal-raspberrypi4 recipe SRC_REV version.
